/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Slobish;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;


/**
 *
 * @author Franco
 */
public class DoctorLogin extends javax.swing.JFrame {
        DriverSQL SQL;
        ParentFollowing PF;
        Icon DoctorImage,CheckImage;
        //ImageSelected = new ImageIcon(getClass().getResource("Images/Mujer0.png"));
    
    /**
     * Creates new form LoginFrame
     * @param SQL
     */
    public DoctorLogin(DriverSQL SQL) {
        this.SQL=SQL;
        initComponents();
        DoctorButton.requestFocus();
        
    }
    public DoctorLogin()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDmedField = new javax.swing.JTextField();
        DoctorButton = new javax.swing.JButton();
        EnglishButton = new javax.swing.JButton();
        SpanishButton = new javax.swing.JButton();
        PassmedField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        IDmedField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        IDmedField.setForeground(new java.awt.Color(102, 102, 102));
        IDmedField.setText("ID...");
        IDmedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDmedFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDmedFieldFocusLost(evt);
            }
        });

        DoctorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/CareStationEnglish.png"))); // NOI18N
        DoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorButtonActionPerformed(evt);
            }
        });

        EnglishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/FlagUSA.png"))); // NOI18N
        EnglishButton.setPreferredSize(new java.awt.Dimension(25, 15));
        EnglishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnglishButtonActionPerformed(evt);
            }
        });

        SpanishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/FlagSPAIN.png"))); // NOI18N
        SpanishButton.setPreferredSize(new java.awt.Dimension(25, 15));
        SpanishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpanishButtonActionPerformed(evt);
            }
        });

        PassmedField.setText("password");
        PassmedField.setToolTipText("Password");
        PassmedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassmedFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EnglishButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpanishButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassmedField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDmedField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(DoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDmedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PassmedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DoctorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnglishButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpanishButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PassmedField.getAccessibleContext().setAccessibleName("Password");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorButtonActionPerformed
      
        GlobalSession GS=null;
        String medField=IDmedField.getText();
        char[] passField=PassmedField.getPassword();
        String passGot = new String(passField);
       /* Menu m = new Menu(SQL,GS,this);
        m.setVisible(true);
        */
       
       ResultSet resultado;
       resultado=SQL.ejecutarSQLSelect("SELECT medicos.IDmed "
                            + " from medicos WHERE Idmed like '" + medField+"'"+" and medicos.Contraseña"
                                    + " like '" + passGot+"'");
            try 
            {
                if (resultado.next())
                {
                    GS= new GlobalSession(medField,passGot);                                    
                    closeWindow();
                    Menu m = new Menu(SQL,GS,this);
                    m.setVisible(true);
                }   
                else
                {
                    JOptionPane.showMessageDialog(this, "Combinacion incorrecta!");
                }
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(DoctorLogin.class.getName()).log(Level.SEVERE, null, ex);
            }      
            
      
    }//GEN-LAST:event_DoctorButtonActionPerformed
public void closeWindow()
{
   this.setVisible(false);    
}
    
    private void EnglishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnglishButtonActionPerformed
        DoctorButton.setIcon(new ImageIcon("Images/CareStationEnglish.png"));
       
        // TODO add your handling code here:
    }//GEN-LAST:event_EnglishButtonActionPerformed

    private void PassmedFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassmedFieldFocusGained
        PassmedField.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_PassmedFieldFocusGained

    private void IDmedFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDmedFieldFocusGained
    
        if(IDmedField.getText().equals("ID...") || IDmedField.getText().isEmpty())
            {
                IDmedField.setText("");
                IDmedField.setForeground(Color.black);
                IDmedField.setFont(new Font("Tahoma",1,11));
            }      
    }//GEN-LAST:event_IDmedFieldFocusGained

    private void IDmedFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDmedFieldFocusLost
         if (IDmedField.getText().equals(""))
        {             
            IDmedField.setFont(new Font("Tahoma",2,11));
            IDmedField.setForeground(new Color(102, 102, 102));
            IDmedField.setText("ID...");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_IDmedFieldFocusLost

    private void SpanishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpanishButtonActionPerformed

        DoctorButton.setIcon(new ImageIcon("Images/CareStationSpanish.png"));

    }//GEN-LAST:event_SpanishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DoctorLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorButton;
    private javax.swing.JButton EnglishButton;
    private javax.swing.JTextField IDmedField;
    private javax.swing.JPasswordField PassmedField;
    private javax.swing.JButton SpanishButton;
    // End of variables declaration//GEN-END:variables
}
