/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Slobish;

import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author Franco
 */
public class Menu extends javax.swing.JFrame {
         DriverSQL SQL;
         GlobalSession GS;
         SetNewWristband1 CF;
         PacientRegister PR;
         OnlineFollowing OF;
         DoctorLogin LF;
         SetNewWristband1 NW;
         DisableWristband DW;
         ConfigurateWristband CW;
         Timer timer1;
         boolean SMdeployed=false;
         boolean SMtimeout=false;
         boolean PRcreated=false;
         boolean CFcreated=false;
         boolean OFcreated=false;
         int state=0;
         
       
    /**
     * Creates new form Menu
     * @param SQL
     * @param GS
     * @param LF
     */
    public Menu(DriverSQL SQL,GlobalSession GS,DoctorLogin LF) {
        this.SQL=SQL;
        this.GS=GS;
        this.LF=LF;
        timer1= new Timer(75, (ActionEvent e) -> {
            switch (state)
            {
                case 0:
                    ConfigurateWristbandButton.setVisible(true);  
                    state++;
                    break;
                case 1:              
                    DisableWristbandButton.setVisible(true);          
                    state++;
                    break;
                case 2:
                    SetNewWristbandButton.setVisible(true);
                    state=0;
                    break;
            }
        });
        timer1.setRepeats(true);
    
        initComponents();
        DisableWristbandButton.setVisible(false);
        ConfigurateWristbandButton.setVisible(false);
        SetNewWristbandButton.setVisible(false);
    }
    public Menu()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckPacient = new javax.swing.JButton();
        OnlineFollowing = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LogOutButton = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        AboutUs = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        ConfigurateWristbandButton = new javax.swing.JButton();
        DisableWristbandButton = new javax.swing.JButton();
        SetNewWristbandButton = new javax.swing.JButton();
        WristbandConfigurate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EirCare");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CheckPacient.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        CheckPacient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/ButtonPacientRegisterEnglish.png"))); // NOI18N
        CheckPacient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPacientActionPerformed(evt);
            }
        });
        getContentPane().add(CheckPacient, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 345, 117));

        OnlineFollowing.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        OnlineFollowing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/ButtonOnlineFollowingEnglish.png"))); // NOI18N
        OnlineFollowing.setPreferredSize(new java.awt.Dimension(387, 57));
        OnlineFollowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineFollowingActionPerformed(evt);
            }
        });
        getContentPane().add(OnlineFollowing, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 345, 117));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/LogoEirCareSmall.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogOutButton.setBackground(new java.awt.Color(255, 153, 153));
        LogOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 105, 38));

        Help.setBackground(new java.awt.Color(204, 255, 255));
        Help.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jPanel1.add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 99, 36));

        AboutUs.setBackground(new java.awt.Color(204, 255, 255));
        AboutUs.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        AboutUs.setText("About us");
        AboutUs.setActionCommand("");
        AboutUs.setBorder(null);
        AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 110, 38));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 553, -1, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 220, 60, 110));

        ConfigurateWristbandButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/ConfigurateWristbandEnglish.png"))); // NOI18N
        ConfigurateWristbandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigurateWristbandButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfigurateWristbandButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 345, 60));

        DisableWristbandButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/DisableWristbandEnglish.png"))); // NOI18N
        DisableWristbandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableWristbandButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DisableWristbandButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 345, 60));

        SetNewWristbandButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/SetNewWristbandEnglish.png"))); // NOI18N
        SetNewWristbandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetNewWristbandButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SetNewWristbandButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 345, 60));

        WristbandConfigurate.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        WristbandConfigurate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Slobish/Images/ButtonConfigurateWristbandEnglish.png"))); // NOI18N
        WristbandConfigurate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WristbandConfigurate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WristbandConfigurateActionPerformed(evt);
            }
        });
        getContentPane().add(WristbandConfigurate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 345, 117));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsActionPerformed
       
       this.setVisible(false); 
       AboutUsFrame j;
       j = new AboutUsFrame(this);
       j.setVisible(true);       
       /*
       WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);   
       */
    }//GEN-LAST:event_AboutUsActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        HelpWindow helpwindow = new HelpWindow();
        helpwindow.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void CheckPacientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPacientActionPerformed
        if (!PRcreated)
        {
            PR = new PacientRegister(SQL,GS);
            PR.setVisible(true);
            PRcreated=true;
        }
        else
        {
            PR.setVisible(true);
        }
    }//GEN-LAST:event_CheckPacientActionPerformed

    private void OnlineFollowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineFollowingActionPerformed
        if (!OFcreated)
        {
            OF = new OnlineFollowing(SQL);
            OF.setVisible(true);
            OFcreated=true;
        }
        else
        {
            OF.setVisible(true);
        }
    }//GEN-LAST:event_OnlineFollowingActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
           
        GS=null;
        this.setVisible(false);
        LF.setVisible(true);       
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void WristbandConfigurateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WristbandConfigurateActionPerformed
        if (SMdeployed==true)
        {
            SMdeployed=false;
            DisableWristbandButton.setVisible(false);
            ConfigurateWristbandButton.setVisible(false);
            SetNewWristbandButton.setVisible(false);
            timer1.stop();
            state=0;
        }
        else
        {
            SMdeployed=true;
            /*
            DisableWristbandButton.setVisible(true);
            ConfigurateWristbandButton.setVisible(true);
            SetNewWristbandButton.setVisible(true);
            */
            timer1.start();
        }
    }//GEN-LAST:event_WristbandConfigurateActionPerformed

    private void SetNewWristbandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetNewWristbandButtonActionPerformed
      NW=null;
      NW = new SetNewWristband1(SQL);
      NW.setVisible(true);  
    // TODO add your handling code here:
    }//GEN-LAST:event_SetNewWristbandButtonActionPerformed

    private void DisableWristbandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisableWristbandButtonActionPerformed
        DW=null;
        DW = new DisableWristband(SQL);
        DW.setVisible(true);
    }//GEN-LAST:event_DisableWristbandButtonActionPerformed

    private void ConfigurateWristbandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurateWristbandButtonActionPerformed
        
        CW=null;
        CW = new ConfigurateWristband(SQL);
        CW.setVisible(true);
    }//GEN-LAST:event_ConfigurateWristbandButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutUs;
    private javax.swing.JButton CheckPacient;
    private javax.swing.JButton ConfigurateWristbandButton;
    private javax.swing.JButton DisableWristbandButton;
    private javax.swing.JButton Help;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton OnlineFollowing;
    private javax.swing.JButton SetNewWristbandButton;
    private javax.swing.JButton WristbandConfigurate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
