/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Slobish;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class ParentLogin extends javax.swing.JFrame {
    
        DriverSQL SQL;
        ResultSet resultado;
        String DNI;
        ParentFollowing PF;
        Color nativeColor;
    /**
     * Creates new form ParentLogin
     * @param SQL
     */
    public ParentLogin(DriverSQL SQL) {
        this.SQL=SQL;
        initComponents();
        LoginButton.requestFocus();
        nativeColor = new Color(102, 102, 102);
    }
    public ParentLogin()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginButton = new javax.swing.JButton();
        UserField = new javax.swing.JTextField();
        PassField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LoginButton.setText("Check");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        UserField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        UserField.setForeground(new java.awt.Color(153, 153, 153));
        UserField.setText("User...");
        UserField.setToolTipText("");
        UserField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UserFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UserFieldFocusLost(evt);
            }
        });

        PassField.setForeground(new java.awt.Color(153, 153, 153));
        PassField.setText("password");
        PassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        
        char[] pass= PassField.getPassword();
        String password=new String(pass);
        String QUERY1 ="SELECT parientes.DNI "
                            + " from parientes WHERE parientes.usuario like '" + UserField.getText()+"'"+" and parientes.contraseña"
                                    + " like '" + password+"'";
        
        resultado=SQL.ejecutarSQLSelect(QUERY1);
        System.out.print(QUERY1);
        
            try 
            {
                if (resultado.next())
                {
                    DNI=resultado.getString("DNI");
                    this.setVisible(false);
                    PF = null;
                    PF = new ParentFollowing(SQL,DNI);
                    PF.setVisible(true);
                    
                }   
                else
                {
                    JOptionPane.showMessageDialog(this, "Combinacion incorrecta!");
                }
            } 
            catch (HeadlessException | SQLException e)
            {
                System.out.println(e);
            }
                  
        
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UserFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserFieldFocusGained
        if(UserField.getText().equals("User..."))
        {
            UserField.setText("");
            UserField.setFont(new Font("Tahoma",1,11));
            UserField.setForeground(Color.black);
        }
    }//GEN-LAST:event_UserFieldFocusGained

    private void UserFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UserFieldFocusLost
        if (UserField.getText().equals("") )
        {
            UserField.setText("User...");
            UserField.setFont(new Font("Tahoma",2,11));
            UserField.setForeground(nativeColor);
        }
    }//GEN-LAST:event_UserFieldFocusLost

    private void PassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassFieldFocusGained
        if(Arrays.toString(PassField.getPassword()).equals("password"))
        {
            PassField.setText("");
            PassField.setFont(new Font("Tahoma",1,11));
            PassField.setForeground(Color.black);
        }
    }//GEN-LAST:event_PassFieldFocusGained

    private void PassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassFieldFocusLost
        
        if(Arrays.toString(PassField.getPassword()).equals(""))
            {
                UserField.setText("password");
                UserField.setFont(new Font("Tahoma",1,11));
                UserField.setForeground(Color.black);
            }
    }//GEN-LAST:event_PassFieldFocusLost
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField UserField;
    // End of variables declaration//GEN-END:variables
}
